# Generated by Django 5.2.14 on 2026-06-02 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_task_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='外部任务ID')),
                ('task_name', models.CharField(max_length=255)),
                ('target_url', models.URLField()),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='外部任务原始数据')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLAIMED', 'Claimed'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='领取客户端账号')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_tasks', to=settings.AUTH_USER_MODEL, verbose_name='发布管理员')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_data', models.JSONField(verbose_name='采集到的JSON数据')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_data', to='tasks.clienttask')),
            ],
        ),
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tasks.clienttask')),
            ],
        ),
        migrations.AddIndex(
            model_name='clienttask',
            index=models.Index(fields=['status', 'created_at', 'id'], name='tasks_clien_status_29dd32_idx'),
        ),
        migrations.AddIndex(
            model_name='clienttask',
            index=models.Index(fields=['assigned_to', 'status'], name='tasks_clien_assigne_8c2f1e_idx'),
        ),
    ]
