# Generated by Django 5.2.14 on 2026-06-04 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clienttask',
            options={'ordering': ['created_at', 'id'], 'verbose_name': '客户端任务', 'verbose_name_plural': '客户端任务'},
        ),
        migrations.AlterModelOptions(
            name='scrapeddata',
            options={'ordering': ['-uploaded_at', '-id'], 'verbose_name': '采集数据', 'verbose_name_plural': '采集数据'},
        ),
        migrations.AlterModelOptions(
            name='tasklog',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': '任务日志', 'verbose_name_plural': '任务日志'},
        ),
        migrations.AlterField(
            model_name='clienttask',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='领取时间'),
        ),
        migrations.AlterField(
            model_name='clienttask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='clienttask',
            name='status',
            field=models.CharField(choices=[('PENDING', '未领取'), ('CLAIMED', '已领取'), ('RUNNING', '进行中'), ('SUCCESS', '已完成'), ('FAILED', '失败')], default='PENDING', max_length=50, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='clienttask',
            name='target_url',
            field=models.URLField(verbose_name='目标链接'),
        ),
        migrations.AlterField(
            model_name='clienttask',
            name='task_name',
            field=models.CharField(max_length=255, verbose_name='任务名称'),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_data', to='tasks.clienttask', verbose_name='所属任务'),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='记录时间'),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='message',
            field=models.TextField(verbose_name='日志内容'),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tasks.clienttask', verbose_name='所属任务'),
        ),
    ]
