# Generated by Django 5.2.14 on 2026-06-04 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_chinese_verbose_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskClaimRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_claimed_at', models.DateTimeField(verbose_name='最近领取时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_claim_record', to=settings.AUTH_USER_MODEL, verbose_name='客户端账号')),
            ],
            options={
                'verbose_name': '任务领取记录',
                'verbose_name_plural': '任务领取记录',
            },
        ),
    ]
