# Generated by Django 5.2.14 on 2026-06-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_claim_cooldown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttask',
            name='status',
            field=models.CharField(choices=[('PENDING', '未领取'), ('CLAIMED', '已领取'), ('RUNNING', '进行中'), ('SUCCESS', '已完成'), ('FAILED', '失败'), ('TIMEOUT', '已超时')], default='PENDING', max_length=50, verbose_name='任务状态'),
        ),
    ]
